apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
spec:
  selector:
    matchLabels:
      app: http
  replicas: 3
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
      - name: http-server
        image: valeriaverboloz/http_server:0.1
        ports:
        - containerPort: 80

        livenessProbe:
          exec:
            command:
            - bash
            - -c
            - 'curl http://localhost:80/healthcheck'
          initialDelaySeconds: 5
          periodSeconds: 5

        readinessProbe:
          exec:
            command:
            - bash
            - -c
            - 'curl http://localhost:80/healthcheck'
          initialDelaySeconds: 5
          periodSeconds: 5
