---
  - name: Localhost Run.
    hosts: localhost
    connection: local 

    # Pre-Tasks to validate if Minikube is running
    pre_tasks:
    - name: Check Minikube's status.
      command: minikube status
      register: minikube_status
      changed_when: false
      ignore_errors: true
      no_log: True

    # Otherwise will start minikube
    - name: Start Minikube.
      command: minikube start --vm-driver=virtualbox
      when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"

    - name: Enable ingress addon.
      command: minikube addons enable ingress
      when: "minikube_status.stdout or 'Running' in minikube_status.stdout"

    tasks:
    - name: Create Deployment.
      command: kubectl create -f ../manifests/deployment.yaml
    
    - name: Sleep for 15 seconds and continue with play.
      wait_for:
        timeout: 15
      delegate_to: localhost

    - name: Create Service and Ingress.
      command: kubectl create -f ../manifests/networking.yaml

    post_tasks:
    - name: Find LB IP
      shell: export lb_ip=$(kubectl get ingress | grep "http-ingress" | awk {'print $4'})

    - name: Print to stdout
      shell: echo $lb_ip
      register: echo

    - debug: msg="Put the output in your /etc/hosts file -> '{{ echo.stdout}} test.com'"


