---
  - name: Localhost Run.
    hosts: localhost
    connection: local

    # Pre-Tasks to validate if Minikube is running
    pre_tasks:
    - name: Check Minikube's status.
      command: minikube status
      register: minikube_status
      changed_when: false
      ignore_errors: true
      no_log: True

    # Otherwise will start minikube
    - name: Start Minikube. Will be ready in few minutes.
      command: minikube start --vm-driver=virtualbox
      when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"

    - name: Enable ingress addon.
      command: minikube addons enable ingress
      when: "minikube_status.stdout or 'Running' in minikube_status.stdout"

    tasks:
    - name: Create Deployment.
      command: kubectl create -f ../manifests/deployment.yaml

    - name: Sleep for 15 seconds and continue with play to have Service ready.
      wait_for:
        timeout: 15
      delegate_to: localhost

    - name: Create Service and Ingress.
      command: kubectl create -f ../manifests/networking.yaml
    
    - name: Sleep for 60 seconds and continue with play to get ingress IP.
      wait_for:
        timeout: 60
      delegate_to: localhost

    post_tasks:
    - name: Get ingress IP
      shell: echo Put the output in your /etc/hosts file ---- $(kubectl get ingress | grep "http-ingress" | awk {'print $4'}) test.com
      register: lb_ip

    - set_fact: ingress_ip="{{ lb_ip.stdout }}"

    - debug: var=ingress_ip
